sudo: false
os:
 - linux
 - osx
language: d
d:
 - dmd-2.071.1
 - ldc-1.1.0-beta2
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: dmd-2.071.1, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.1.0-beta2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
    - stable
    - tinflex2
cache:
  directories:
    - $HOME/.cache/matplotlib
    # macOS is special ...
    - $HOME/.matplotlib
script:
 - echo "$ARCH"
 - dub test --arch "$ARCH" -b unittest-cov
 - dub build --single examples/lda_hoffman_sparse.d
 - dub fetch imageformats --version 6.0.0 && dub build imageformats
 - dub build --single examples/median_filter.d
 - dub build --single examples/means_of_columns.d

 ######## Setup python
 - if [ ${TRAVIS_OS_NAME} = "linux" ] ; then
     wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
   else
     wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh ;
   fi
 - bash miniconda.sh -b -f -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a
 - conda create --yes -n condaenv python=3.5 || true
 - conda install --yes -n condaenv matplotlib
 - source activate condaenv
 - python -c 'import matplotlib as mpl; print(mpl.get_cachedir());print(mpl._version)'
 # conda and macOS is messed up, but we can manually set all required paths
 - if [ ${TRAVIS_OS_NAME} = "osx" ] ; then
    export PYTHONPATH=$HOME/miniconda/lib/python3.5:$HOME/miniconda/lib/python3.5/lib-dynload:$HOME/miniconda/envs/condaenv/lib/python3.5/site-packages ;
   fi
 ######## End setup python

 # workaround against dub bugs
 - dub build --root=examples/flex_plot
 - dub build --root=examples/flex_plot/flex_common
 # dub needs to find libpython3.5m.so
 - MPLBACKEND="agg" LD_LIBRARY_PATH=$HOME/miniconda/lib LIBRARY_PATH=$HOME/miniconda/lib/ dub --single examples/flex_plot.d -- normal
 - ls ~/.matplotlib
 - ls -al ~
 # check that we created a valid file
 - if [ ${TRAVIS_OS_NAME} = "osx" ] ; then
     if [ $(stat -f%z plots/dist_normal_hs.pdf) -le 20000 ] ; then exit 1; fi ;
   else
     if [ $(stat -c%s plots/dist_normal_hs.pdf) -le 20000 ] ; then exit 1; fi
   fi
 # this file always changes (forces to repack the cache)
 - rm -f $HOME/miniconda/lib/python3.5/__pycache__/_sysconfigdata.cpython-35.pyc
after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
