sudo: false
os:
 - linux
 - osx
language: d
d:
 - dmd-2.071.0
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - ldc-1.0.0-alpha1
 - ldc-0.17.0
install:
 - if [[ $(dmd --help | head -n 1 | cut -d ' ' -f 4) == 'v2.071.0' && $TRAVIS_OS_NAME == 'linux' ]] ; then export IS_LATEST_PHOBOS=1 ; fi
 - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.2.0/doveralls_linux_travis"
 - chmod +x doveralls
 - wget -O dscanner "http://releases.dlang.io/dscanner/0.3.0-git/dscanner"
 - chmod +x dscanner
script:
 - if [ "$IS_LATEST_PHOBOS" ] ; then ./dscanner --config .dscanner.ini --styleCheck source 2> /dev/null ; else echo "NOT_LATEST"; fi
 - dub test -b unittest-cov
after_success:
 - bash <(curl -s https://codecov.io/bash)
