platform: x64
environment:
 matrix:
  - DC: ldc
    DVersion: 1.1.0-beta2
    arch: x64

skip_tags: true
branches:
  only:
    - master
    - stable

install:
  - ps: function SetUpDCompiler
        {
          echo "downloading ...";
          if($env:arch -eq "x86"){
            $env:DConf = "m32";
          }
          elseif($env:arch -eq "x64"){
            $env:DConf = "m64";
          }
          $env:toolchain = "msvc";
          $version = $env:DVersion;
          Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win64-msvc.zip" -OutFile "c:\ldc.zip";
          echo "finished.";
          pushd c:\\;
          7z x ldc.zip > $null;
          popd;
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest https://code.dlang.org/files/dub-1.0.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps:
        $version = $env:DVersion;
        $env:PATH += ";C:\ldc2-$($version)-win64-msvc\bin";
        $env:DC = "ldmd2";
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me
 #- sed 's/"to_be_filled"/"Flex_logging", "Flex_logging_hex"/' -i dub.json
 # For now only python 3.4 is supported with pyd
 - sed 's/python35/python34/' -i examples/flex_plot.d
 - sed 's/python35/python34/' -i examples/flex_plot/flex_common/dub.json

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - '%DC% --version'
 - dub fetch cpuid && dub build --arch %Darch% cpuid
 - dub test --arch %Darch% --build=unittest-cov
 - dub test --arch %Darch% --build=unittest-release
 - dub build --single --arch %Darch% examples/lda_hoffman_sparse.d
 - dub fetch imageformats --version 6.1.0 && dub build --arch %Darch% imageformats
 - dub build --single --arch %Darch% examples/median_filter.d
 - dub build --single --arch %Darch% examples/means_of_columns.d
 - dub build --root=examples/flex_plot --arch %Darch%
 - dub build --root=examples/flex_plot/flex_common --arch %Darch%

notifications:
 - provider: Webhook
   url: https://webhooks.gitter.im/e/56aae174f8cc81f4eda4
 - provider: Email
   to:
    - devteam@mir.rocks
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
